### ISSUE TITLE
Link to 1.2.19 docs return a 500

### ISSUE THREAD

**Issue by mkelley33** [angular/code.angularjs.org#12]
I tried to visit the API docs for AngularJS 1.2.19 and got a 500 server error.

To reproduce:

1. go to https://docs.angularjs.org/api/
2. from drop API reference at top of page, select v1.2.19 from drop-down select menu 
3. you'll be taken to https://code.angularjs.org/1.2.19/docs/api/ which returns a standard nginx server 500 error message

![screen shot 2014-07-12 at 8 30 10 pm](https://cloud.githubusercontent.com/assets/213627/3563228/f9eac770-0a25-11e4-8e06-8617c05237f5.png)

**Comment by supasate** [comment]
This issue can be closed. It works now.

**Comment by mkelley33** [comment]
Closing, verified as fixed.  Thanks @supasate
