### ISSUE TITLE
Two folders (leading to 404 pages) randomly appear at the root

### ISSUE THREAD

**Issue by joelross** [angular/code.angularjs.org#15]
Hello

I see two folders that seem to randomly appear at the root of https://code.angularjs.org/ named **angular-1.2.15-build.2376+sha.66fdc03/** and **angular-1.3.1-build.3436+sha.47e15aa/**. Both links simply lead to a standard `404 Not Found` page. They seem to randomly appear about 1/3 of the times.

I have tried from several internet connections and several machines/browsers, and there was no differences. So I don't think it's a proxy/cache issue on my side.

![angular](https://cloud.githubusercontent.com/assets/2394159/5959164/03d0afb8-a7cc-11e4-933a-45b646d5da24.png)

**Comment by Narretz** [comment]
Probably a cache issue that is likely resolved by now,
