### ISSUE TITLE
Add system-polyfills for IE/Edge users

### ISSUE THREAD

**Issue by robwormald** [angular/code.angularjs.org#30]
See https://github.com/angular/angular/issues/5426

**Comment by pkozlowski-opensource** [comment]
Could we rather add es6 shim? See info copied over from https://github.com/angular/angular/issues/5426#issuecomment-158617554

The thing is that SystemJS will try to download polyffils for things like Promise etc. (which I really don't think it should be doing...). But it won't do it if things are needed are already available. 

So imo a "proper" way of solving this is to include es6 shim _before_ SystemJS - you will need those for IE anyway and it will prevent SystemJS from firing its XHR little thingy thus saving one round-trip to a server.

Deploying system-polyfills.js won't hurt but it might put users on sub-optimal track. So I would rather vote for deploying es6 shim.

**Comment by tenowg** [comment]
I will attempt again later, but I did look at the appendix on the 5 minute
quick start, and tried to include es6shim and it still required
system-polyfills and would fail to load the app.

**Comment by tenowg** [comment]
Attempting to add es6-shim will still fail without system-ployfills on Edge (not tested on lower versions)

below I show that es6-shim is loaded:

![loaded](https://cloud.githubusercontent.com/assets/1147426/11353351/57a9ec1a-9210-11e5-9dd2-c8070edb94e0.PNG)

and also the attempt to load the system-polyfills:

![notfound](https://cloud.githubusercontent.com/assets/1147426/11353363/6a07fb86-9210-11e5-89ae-d32ad0f0e482.PNG)

this of course leads to this messge:

![errormessage](https://cloud.githubusercontent.com/assets/1147426/11353393/b86f4f18-9210-11e5-9630-7fd35a28c861.PNG)

So currently system-polyfills is required to get the quick start working for new users that don't want to have to jump through hoops to try out angular2
