### ISSUE TITLE
DOM XSS

### ISSUE THREAD

**Issue by BSec** [angular/code.angularjs.org#34]
Issue @ **[](https://github.com/angular/code.angularjs.org/blob/master/1.2.14/angular.js)**

Javsscript code:
**_window.name = window.name.replace(NG_DEFER_BOOTSTRAP, '');_**

Security Issue: **Can lead to DOM XSS.**
Kindly fix it.

Regards
BSec

**Comment by Narretz** [comment]
Bugs / Feature Requests must be reported at: https://github.com/angular/angular.js/issues
