### ISSUE TITLE
Uncaught ReferenceError: Node is not defined

### ISSUE THREAD

**Issue by minchopm** [angular/code.angularjs.org#37]
Hi,
I all versions after 1.5.0 I am getting 
Uncaught ReferenceError: Node is not defined
because the check for Node is not correct.
Please update in next version that line:
var jqLiteContains = Node.prototype.contains || function(arg) {
to
var jqLiteContains = Node && Node.prototype.contains || function(arg) {

**Comment by Narretz** [comment]
Bugs / Feature Requests must be reported at: https://github.com/angular/angular.js/issues
